Repository NREL/OpenStudio-resources, pull requests merged in 2021-01, with the labels that each got.

#125 Addresses #3992, chiller ReformulatedEIR model
  model/simulationtests/chiller_reformulated.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#124 Addresses #3615, wrap Refrigeration:CompressorRack in OpenStudio
  model/simulationtests/refrigeration_system_2.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#121 Addresses #1972, add Humidifier:Steam:Gas
  model/simulationtests/humidity_control_2.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#122 Addresses #2958, add ZoneHVAC:CoolingPanel:RadiantConvective:Water to OpenStudio
  model/simulationtests/zone_hvac_cooling_panel.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#123 Add a test for #4175 - ELCD without generators
  model/simulationtests/elcd_no_generators.rb
  model_tests.rb
Labels: NewTestForExisting, PendingOSM

#119 Align PTAC and PTHP coils with EnergyPlus
  model/simulationtests/ptac_othercoils.rb
  model/simulationtests/pthp_othercoils.rb
  model_tests.rb
Labels: NewTestForExisting, PendingOSM

#115 Add new test for multiple shading controls
  SDD_tests.rb
  model/simulationtests/shadingcontrol_singlezone.osm
  model/simulationtests/shadingcontrol_singlezone.rb
  model_tests.rb
Labels: AddedOSM, NewTest

#130 Fix #129 - Add test-stability in Github Actions + skip ci
  .github/workflows/pull_request.yml
  environment.yml
  process_results.py
  python/regression_analysis.py
  requirements.txt
Labels: Developper Issue, enhancement
