Repository NREL/OpenStudio-resources, pull requests merged in 2022-09, with the labels that each got.

#172 Addresses #3666, new test for Coil:WaterHeating:Desuperheater with Refrigeration:Condenser:AirCooled heating source
  model/simulationtests/coil_waterheating_desuperheater_2.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#164 Addresses #4311, add water heaters to supply side of different loops
  model/simulationtests/heatrecovery_chiller.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#174 Remove deprecated methods for AirWallMaterial, Node, SizingSystem, ZoneAirMassFlowConservation
  model/refbuildingtests/measures/AddHVACSystem.rb
  model/simulationtests/afn_single_zone_ac.rb
  model/simulationtests/availability_managers.rb
  model/simulationtests/lib/baseline_model.rb
  model/simulationtests/lifecyclecostparameters.rb
  model/simulationtests/moisture_settings.rb
  model/simulationtests/zone_fan_exhaust.rb
  model/simulationtests/zone_mixing.rb
Labels: TestFix

#173 Addresses #4647, wrap the E+ Table:Lookup, Table:IndependentVariableList, and Table:IndependentVariable objects
  model/simulationtests/airterminal_fourpipebeam.rb
  model/simulationtests/tablelookup.rb
  model/simulationtests/tablemultivariablelookup.rb
  model_tests.rb
Labels: TestFix

#178 Update to v22.2.0-IOFreeze
  model/simulationtests/autosize_hvac.rb
Labels: Other

#161 Timings ci refactor
  .gitignore
  Timings_VT_OSM.ipynb
  model/simulationtests/airloop_and_zonehvac.rb
  model/simulationtests/autosize_hvac.rb
  model/simulationtests/baseline_sys01.rb
  model/simulationtests/zone_hvac.rb
  performance_baseline.py
  performance_test.py
  python/__init__.py
  python/performance.py
Labels: Other, Developer Issue

#177 Fix #4648 #4654 - SurfaceProperty:GroundSurfaces and SurfaceProperty:IncidentSolarMultiplier
  model/simulationtests/surface_properties_ground_and_solarmult.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#179 Fix #4656 - E+ 22.2.0: Wrap Chiller:Electric:ASHRAE205
  model/simulationtests/CoolSys1-Chiller-Detailed.RS0001.a205.cbor
  model/simulationtests/autosize_hvac.rb
  model/simulationtests/chiller_electric_ashrae205.rb
  model_tests.rb
Labels: NewTest, PendingOSM

#183 Add Output:Constructions and Output:Schedules
  model/simulationtests/output_objects_2.rb
Labels: NewTest, PendingOSM
